export const hiringData = [
  {
    company: "AT KEARNEY",
    hires: [
      { school: "University of Chicago", count: 13 },
      { school: "University of Michigan", count: 9 },
      { school: "INSEAD", count: 9 },
      { school: "Northwestern", count: 7 },
      { school: "University of Virginia", count: 6 },
      { school: "University of Navarra", count: 5 },
      { school: "The University of Western Ontario", count: 4 },
      { school: "Ohio State University", count: 3 },
      { school: "Thunderbird", count: 3 },
      { school: "Arizona State University", count: 3 },
      { school: "Erasmus University", count: 2 },
    ],
  },
  {
    company: "BAIN",
    hires: [
      { school: "University of Pennsylvania", count: 36 },
      { school: "INSEAD", count: 29 },
      { school: "Northwestern University", count: 12 },
      { school: "Massachusetts Institute of Technology", count: 9 },
      { school: "University of Michigan", count: 8 },
      { school: "Dartmouth", count: 6 },
      { school: "Duke University", count: 5 },
      { school: "University of Virginia", count: 5 },
      { school: "Bocconi University", count: 5 },
    ],
  },
  {
    company: "BANK OF AMERICA",
    hires: [
      { school: "The University of North Carolina at Chapel Hill", count: 12 },
      { school: "Wake Forest University", count: 7 },
      { school: "Duke University", count: 6 },
      { school: "Vanderbilt University", count: 5 },
      { school: "Texas A&M University", count: 4 },
      { school: "Brigham Young University", count: 3 },
      { school: "Indiana University", count: 3 },
      { school: "University of South Carolina", count: 3 },
      { school: "University of Southern California", count: 3 },
      { school: "Georgia Institute of Technology", count: 2 },
      { school: "University of Florida", count: 2 },
      { school: "University of Georgia", count: 2 },
      { school: "University of Connecticut", count: 1 },
    ],
  },
  {
    company: "BARCLAY'S",
    hires: [
      { school: "INSEAD", count: 19 },
      { school: "University of London", count: 12 },
      { school: "University of Navarra", count: 5 },
      { school: "Yale University", count: 4 },
      { school: "University of Rochester", count: 3 },
      { school: "RSM Erasmus University", count: 2 },
      // Add more schools here...
    ],
  },
  {
    company: "BOOZ ALLEN HAMILTON",
    hires: [
      { school: "Columbia University", count: 20 },
      { school: "Northwestern University", count: 18 },
      { school: "University of Pennsylvania", count: 13 },
      { school: "University of London", count: 9 },
      { school: "INSEAD", count: 9 },
      { school: "Carnegie Mellon University", count: 8 },
      { school: "University of Michigan", count: 8 },
      { school: "Georgetown University", count: 7 },
      { school: "Yale University", count: 5 },
      { school: "University of Navarra", count: 5 },
      { school: "The University of North Carolina at Chapel Hill", count: 3 },
      { school: "The College of William and Mary", count: 1 },
      // Add more schools here...
    ],
  },
  {
    company: "BOSTON CONSULTING",
    hires: [
      { school: "INSEAD", count: 60 },
      { school: "University of Pennsylvania", count: 39 },
      { school: "Northwestern University", count: 25 },
      { school: "Columbia University", count: 19 },
      { school: "The University of Iowa", count: 16 },
      { school: "Dartmouth College", count: 12 },
      { school: "Massachusetts Institute of Technology", count: 9 },
      { school: "University of Navarra", count: 9 },
      { school: "University of Virginia", count: 7 },
      { school: "University of London", count: 6 },
      { school: "University of California, Berkeley", count: 4 },
      { school: "Yale University", count: 4 },
      { school: "Bocconi University", count: 3 },
      { school: "HEC Paris", count: 3 },
      // Add more schools here if needed
    ],
  },
  {
    company: "CIBC",
    hires: [
      { school: "York University", count: 21 },
      { school: "The University of Western Ontario", count: 22 },
      { school: "University of Toronto", count: 12 },
      // Add more schools here if needed
    ],
  },
  {
    company: "CITIGROUP",
    hires: [
      { school: "Columbia University", count: 25 },
      { school: "University of Pennsylvania", count: 22 },
      { school: "University of Chicago", count: 19 },
      { school: "Cornell University", count: 12 },
      { school: "University of Michigan", count: 11 },
      { school: "Georgetown University", count: 9 },
      { school: "Duke University", count: 8 },
      { school: "INSEAD", count: 8 },
      { school: "Massachusetts Institute of Technology", count: 7 },
      { school: "University of Rochester", count: 7 },
      { school: "University of London", count: 7 },
      { school: "University of Maryland", count: 6 },
      { school: "University of Virginia", count: 6 },
      { school: "Carnegie Mellon University", count: 5 },
      { school: "Yale University", count: 5 },
      { school: "University of Navarra", count: 5 },
      { school: "Rice University", count: 4 },
      { school: "Thunderbird", count: 4 },
      { school: "Bocconi University", count: 4 },
      { school: "Baruch College", count: 3 },
      { school: "Boston University", count: 3 },
      { school: "The Pennsylvania State University", count: 3 },
      { school: "Washington University in St. Louis", count: 3 },
      { school: "Fordham University", count: 2 },
      { school: "Texas A&M University", count: 2 },
      { school: "University of Tennessee", count: 2 },
      { school: "ESADE", count: 2 },
      { school: "Texas Christian University", count: 1 },
      { school: "University of Arizona", count: 1 },
      { school: "University of South Carolina", count: 1 },
      { school: "Tecnologico de Monterrey", count: 1 },
      // Add more schools here if needed
    ],
  },
  {
    company: "DELOITTE & TOUCHE",
    hires: [
      { school: "University of California Los Angeles", count: 13 },
      { school: "Northwestern University", count: 12 },
      { school: "The University of Western Ontario", count: 11 },
      { school: "University of Michigan", count: 10 },
      { school: "Louisiana State University", count: 7 },
      { school: "The University of North Carolina at Chapel Hill", count: 7 },
      { school: "University of Maryland", count: 7 },
      { school: "Cornell University", count: 6 },
      { school: "Duke University", count: 6 },
      { school: "University of Texas at Austin", count: 6 },
      { school: "University of Southern California", count: 6 },
      { school: "York University", count: 6 },
      { school: "Emory University", count: 5 },
      { school: "Massachusetts Institute of Technology", count: 5 },
      { school: "University of California, Berkeley", count: 5 },
      { school: "University of Virginia", count: 5 },
      { school: "University of London", count: 5 },
      { school: "Rice University", count: 4 },
      { school: "University of Minnesota", count: 4 },
      { school: "Vanderbilt University", count: 4 },
      { school: "Yale University", count: 4 },
      { school: "University of Toronto", count: 4 },
      { school: "Babson College", count: 3 },
      { school: "Fordham University", count: 3 },
      { school: "Georgia Institute of Technology", count: 3 },
      {
        school: "University at Buffalo State University of New York",
        count: 3,
      },
      { school: "University of Pittsburgh", count: 3 },
      { school: "University of Rochester", count: 3 },
      { school: "University of California, Irvine", count: 2 },
      { school: "University of Denver", count: 2 },
      { school: "University of Miami", count: 2 },
      { school: "University of Notre Dame", count: 2 },
      { school: "University of Tennessee", count: 2 },
      { school: "RSM Erasmus University", count: 2 },
      { school: "George Washington University", count: 1 },
      { school: "Rutgers University", count: 1 },
      { school: "Texas Christian University", count: 1 },
      { school: "University of Arizona", count: 1 },
      { school: "Tecnologico de Monterrey", count: 1 },
    ],
  },
  {
    company: "G.E.",
    hires: [
      { school: "Cornell University", count: 8 },
      { school: "Bocconi University", count: 6 },
      { school: "Yale University", count: 5 },
      { school: "University of Navarra", count: 5 },
      { school: "HEC Paris", count: 5 },
      { school: "The University of Iowa", count: 4 },
      { school: "Vanderbilt University", count: 4 },
      { school: "Babson College", count: 3 },
      { school: "Brigham Young University", count: 3 },
      { school: "Indiana University", count: 3 },
      { school: "University of Minnesota", count: 3 },
      { school: "University of Connecticut", count: 3 },
      { school: "Georgia Institute of Technology", count: 3 },
      { school: "ESADE", count: 3 },
      { school: "Ohio State University", count: 2 },
      { school: "University of Wisconsin-Madison", count: 2 },
      { school: "RSM Erasmus University", count: 2 },
      { school: "IMD", count: 2 },
      { school: "University of Georgia", count: 2 },
      {
        school: "University at Buffalo State University of New York",
        count: 1,
      },
    ],
  },
  {
    company: "GOLDMAN SACHS",
    hires: [
      { school: "University of Pennsylvania", count: 28 },
      { school: "Columbia University", count: 22 },
      { school: "University of Chicago", count: 12 },
      { school: "Massachusetts Institute of Technology", count: 5 },
      { school: "University of California Los Angeles", count: 4 },
      { school: "Dartmouth College", count: 3 },
      { school: "Baruch College/City University of NY", count: 2 },
      { school: "The University of Iowa", count: 2 },
      { school: "Fordham University", count: 1 },
      { school: "University of South Carolina", count: 1 },
    ],
  },
  {
    company: "I.B.M.",
    hires: [
      { school: "Carnegie Mellon University", count: 11 },
      { school: "Yale University", count: 10 },
      { school: "University of Texas at Austin", count: 9 },
      { school: "University of Notre Dame", count: 9 },
      { school: "York University", count: 8 },
      { school: "Emory University", count: 7 },
      { school: "University of California Los Angeles", count: 6 },
      { school: "Cornell University", count: 5 },
      { school: "Massachusetts Institute of Technology", count: 5 },
      { school: "University of Virginia", count: 5 },
      { school: "Georgia Institute of Technology", count: 4 },
      { school: "The University of North Carolina at Chapel Hill", count: 4 },
      { school: "Boston University", count: 3 },
      { school: "University of Wisconsin-Madison", count: 3 },
      { school: "Babson College", count: 2 },
      { school: "Purdue University", count: 2 },
      { school: "Texas A&M University", count: 2 },
      { school: "The College of William and Mary", count: 2 },
      {
        school: "University at Buffalo State University of New York",
        count: 2,
      },
      { school: "University of Arizona", count: 2 },
      { school: "University of California, Davis", count: 1 },
      { school: "University of Miami", count: 1 },
      { school: "University of Tennessee", count: 1 },
    ],
  },
  {
    company: "INTEL",
    hires: [
      { school: "Thunderbird", count: 10 },
      { school: "University of Texas at Austin", count: 5 },
      { school: "Arizona State University", count: 5 },
      { school: "Brigham Young University", count: 4 },
      { school: "Indiana University", count: 4 },
      { school: "Michigan State University", count: 4 },
      { school: "The Pennsylvania State University", count: 4 },
      { school: "University of Notre Dame", count: 4 },
      { school: "University of Maryland", count: 3 },
      { school: "Boston University", count: 2 },
      { school: "University of California, Davis", count: 2 },
      { school: "University of Southern California", count: 2 },
      { school: "University of Wisconsin-Madison", count: 2 },
      { school: "University of Arizona", count: 1 },
      { school: "University of Colorado at Boulder", count: 1 },
    ],
  },
  {
    company: "JOHNSON & JOHNSON",
    hires: [
      { school: "Duke University", count: 25 },
      { school: "University of Pennsylvania", count: 15 },
      { school: "Northwestern University", count: 13 },
      { school: "University of Notre Dame", count: 9 },
      { school: "Thunderbird", count: 8 },
      { school: "RSM Erasmus University", count: 7 },
      { school: "Massachusetts Institute of Technology", count: 6 },
      { school: "Bocconi University", count: 6 },
      { school: "Michigan State University", count: 5 },
      { school: "University of Illinois at Urbana-Champaign", count: 5 },
      { school: "University of Toronto", count: 5 },
      { school: "Cornell University", count: 4 },
      { school: "University of California, Berkeley", count: 4 },
      { school: "University of Pittsburgh", count: 4 },
      { school: "University of Rochester", count: 4 },
      { school: "HEC Paris", count: 4 },
      { school: "The University of Western Ontario", count: 4 },
      { school: "University of Florida", count: 3 },
      { school: "Rutgers University", count: 1 },
      {
        school: "University at Buffalo State University of New York",
        count: 1,
      },
    ],
  },
  {
    company: "J.P. MORGAN",
    hires: [
      { school: "University of Virginia", count: 10 },
      { school: "University of Michigan", count: 7 },
      { school: "Northwestern University", count: 6 },
      { school: "Dartmouth College", count: 4 },
      { school: "The University of North Carolina at Chapel Hill", count: 4 },
      { school: "Rice University", count: 3 },
      { school: "University of Southern California", count: 3 },
      { school: "Vanderbilt University", count: 3 },
    ],
  },
  {
    company: "LEHMAN",
    hires: [
      { school: "Columbia University", count: 28 },
      { school: "University of Chicago", count: 21 },
      { school: "University of Pennsylvania", count: 16 },
      { school: "Duke University", count: 13 },
      { school: "University of Michigan", count: 11 },
      { school: "Dartmouth College", count: 9 },
      { school: "Cornell University", count: 7 },
      { school: "University of Virginia", count: 7 },
      { school: "University of London", count: 7 },
      { school: "University of California Los Angeles", count: 6 },
      { school: "University of Navarra", count: 6 },
      { school: "University of California, Berkeley", count: 5 },
      { school: "Georgetown University", count: 4 },
      { school: "The University of North Carolina at Chapel Hill", count: 4 },
      { school: "Baruch College", count: 2 },
      { school: "Washington University in St. Louis", count: 2 },
      { school: "University of Connecticut", count: 1 },
    ],
  },
  {
    company: "MCKINSEY",
    hires: [
      { school: "INSEAD", count: 90 },
      { school: "University of Pennsylvania", count: 57 },
      { school: "Northwestern University", count: 38 },
      { school: "University of Chicago", count: 38 },
      { school: "Columbia University", count: 31 },
      { school: "Massachusetts Institute of Technology", count: 24 },
      { school: "University of London", count: 12 },
      { school: "University of California, Berkeley", count: 11 },
      { school: "Dartmouth College", count: 10 },
      { school: "Duke University", count: 9 },
      { school: "University of Michigan", count: 8 },
      { school: "University of Navarra", count: 8 },
      { school: "University of California Los Angeles", count: 6 },
      { school: "Yale University", count: 5 },
      { school: "Cornell University", count: 4 },
      { school: "University of Texas at Austin", count: 4 },
      { school: "Bocconi University", count: 3 },
      { school: "HEC Paris", count: 3 },
    ],
  },
  {
    company: "MERRILL LYNCH",
    hires: [
      { school: "University of Chicago", count: 11 },
      { school: "Duke University", count: 7 },
      { school: "Massachusetts Institute of Technology", count: 6 },
      { school: "Georgetown University", count: 5 },
      { school: "Rice University", count: 5 },
      { school: "University of Virginia", count: 5 },
      { school: "University of Rochester", count: 3 },
      { school: "University of Toronto", count: 1 },
    ],
  },
  {
    company: "MORGAN STANLEY",
    hires: [
      { school: "Columbia University", count: 15 },
      { school: "University of Pennsylvania", count: 15 },
      { school: "University of London", count: 6 },
      { school: "Dartmouth College", count: 5 },
      { school: "Babson College", count: 2 },
    ],
  },
  {
    company: "PRICEWATERHOUSE COOPERS",
    hires: [
      { school: "Yale University", count: 10 },
      { school: "Emory University", count: 6 },
      { school: "University of California, Irvine", count: 5 },
      { school: "University of Notre Dame", count: 4 },
      { school: "University of Toronto", count: 4 },
      { school: "George Washington University", count: 3 },
      { school: "Georgia Institute of Technology", count: 3 },
      { school: "Louisiana State University", count: 3 },
      { school: "The Pennsylvania State University", count: 3 },
      { school: "University of Denver", count: 3 },
      { school: "University of Maryland", count: 3 },
      { school: "Baruch College", count: 2 },
      { school: "Michigan State University", count: 2 },
      { school: "Ohio State University", count: 2 },
      { school: "University of Connecticut", count: 2 },
      { school: "ESADE", count: 1 },
    ],
  },
  // Continue adding other companies in a similar format...
];
