export const questions = [
  {
    question_id: 1,
    main_question_stem:
      "In a locality, there are thrice as many buses as cabs. 10% of the buses are air-conditioned while 60% of the cabs are air-conditioned. If there are only these 2 types of vehicles, what percentage of the vehicles are air-conditioned?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "0.225",
    answer_2: "0.25",
    answer_3: "0.3",
    answer_4: "0.333",
    answer_5: "0.36",
    correct_answer: "A",
    Category: "Quant",
    "Sub-category": "Percentage",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 1,
  },
  {
    question_id: 2,
    main_question_stem:
      "In a school, 20% of the boys learn French while 60% of the students who learn French are girls. If there are 100 boys, how many girls learn French?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "20",
    answer_2: "24",
    answer_3: "30",
    answer_4: "36",
    answer_5: "45",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Percentage",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 2,
  },
  {
    question_id: 1,
    main_question_stem:
      "A and B need to do the laundry since their washing machine broke down. A can wash 1/3rd of the clothes in 30 minutes. Both A and B can wash all the clothes in 1 hour. What fraction of the clothes can B wash in 20 minutes?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "1/12",
    answer_2: "1/9",
    answer_3: "1/8",
    answer_4: "1/6",
    answer_5: "1/3",
    correct_answer: "B",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 3,
  },
  {
    question_id: 2,
    main_question_stem:
      "A can write 10 programming codes in 15 hours, and B can write the same codes in 12 hours. If A and B work together on the codes, what fraction of the total work would B have done more than A after 3 hours?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "1/5",
    answer_2: "3/10",
    answer_3: "1/3",
    answer_4: "9/20",
    answer_5: "1/2",
    correct_answer: "D",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 4,
  },
  {
    question_id: 3,
    main_question_stem:
      "A and B can paint 3 walls in 2 hours. Along with C, they can paint 5 walls in 3 hours. If A and C work at the same rate, how long would B take to paint 2 walls?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "1.5 hours",
    answer_2: "1.8 hours",
    answer_3: "2 hours",
    answer_4: "2.5 hours",
    answer_5: "3 hours",
    correct_answer: "A",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 5,
  },
  {
    question_id: 4,
    main_question_stem:
      "Machines A and B can polish 3 articles in 2 hours and 5 articles every 4 hours. If the efficiency of A were tripled and that of B doubled, how long would the 2 machines together take to polish 70 articles?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "10 hours",
    answer_2: "12 hours",
    answer_3: "15 hours",
    answer_4: "16 hours",
    answer_5: "20 hours",
    correct_answer: "A",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 6,
  },
  {
    question_id: 5,
    main_question_stem:
      "A and B can complete a work in 15 days. The same work can be completed by A and C in 20 days. If B is twice as efficient as C, in how many days can A complete the work alone?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "20 days",
    answer_2: "24 days",
    answer_3: "22.5 days",
    answer_4: "27.5 days",
    answer_5: "30 days",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 7,
  },
  {
    question_id: 6,
    main_question_stem:
      "A water pipe fills a tank at the rate of 20 litres in every 8 minutes. A second water pipe fills the tank at 20 litres in half the time of the above pipe. The tank capacity is 720 litres and a 3rd pipe along with the above 2 pipes together fill the tank in 80 minutes. At what rate per minute does the 3rd pipe fill?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "1 litre/min",
    answer_2: "1.2 litre/min",
    answer_3: "1.5 litre/min",
    answer_4: "1.6 litre/min",
    answer_5: "1.8 litre/min",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 8,
  },
  {
    question_id: 7,
    main_question_stem:
      "A water pipe fills a tank at the rate of 5 litres in every minute. Along with another water pipe, it fills the tank in 30 minutes. If the efficiency of the 2nd pipe were doubled, the time taken to fill the tank along with the 1st pipe would have been 18 minutes. What is the capacity of the tank?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "90 litres",
    answer_2: "105 litres",
    answer_3: "120 litres",
    answer_4: "135 litres",
    answer_5: "150 litres",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 9,
  },
  {
    question_id: 8,
    main_question_stem:
      "20 men can do a work in 12 days and 30 women can do double the same work in 36 days. How many days would 8 men and 12 women together take to complete the work?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "6 days",
    answer_2: "8 days",
    answer_3: "12 days",
    answer_4: "16 days",
    answer_5: "18 days",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 10,
  },
  {
    question_id: 9,
    main_question_stem:
      "4 people can paint 8 walls in 6 days. The 4 people worked on painting the 8 walls for 2 days. Thereafter, another 2 people joined them. In how many days would the 6 people paint the remaining of the 8 walls?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "4/3 days",
    answer_2: "2 days",
    answer_3: "8/3 days",
    answer_4: "3 days",
    answer_5: "9/2 days",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 11,
  },
  {
    question_id: 10,
    main_question_stem:
      "In a college, 3 automated exam-paper grading machines working at a constant rate, can grade 36 answer sheets per hour. The college installs 1 more automated exam-paper grading machine that is twice as efficient as the ones above. In how many hours can these machines grade 240 answer sheets?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "2.7 hours",
    answer_2: "3 hours",
    answer_3: "3.6 hours",
    answer_4: "4 hours",
    answer_5: "6 hours",
    correct_answer: "D",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 12,
  },
  {
    question_id: 11,
    main_question_stem:
      "A and B can do a work in 12 days. B and C can complete the same work in 20 days. If A works for 6 days and C works for 10 days, how many days should B work to complete the remaining work?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "8 days",
    answer_2: "10 days",
    answer_3: "12 days",
    answer_4: "15 days",
    answer_5: "16 days",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Rate and Work",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 13,
  },
  {
    question_id: 1,
    main_question_stem:
      "In a college, the ratio of number of students to teachers is 12 : 1 and the ratio of non-teaching staff to students and teachers combined is 11 : 3. What percent of the people above are teachers?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "0.0045",
    answer_2: "0.0056",
    answer_3: "0.0123",
    answer_4: "0.0165",
    answer_5: "0.0189",
    correct_answer: "D",
    Category: "Quant",
    "Sub-category": "Ratios",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 14,
  },
  {
    question_id: 2,
    main_question_stem:
      "If the ratio of (2x + 3y) to (3x â€“ y) is 7 to 3, what is the ratio of (3x + 2y) to (x + 3y)?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "28 : 17",
    answer_2: "31 : 23",
    answer_3: "37 : 29",
    answer_4: "59 : 41",
    answer_5: "78 : 61",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Ratios",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 15,
  },
  {
    question_id: 3,
    main_question_stem:
      "The ratio of men to women in a group is 6 : 5. The ratio of men with and without glasses is 2 : 3 and the ratio of women with and without glasses is 1 : 1. What is the fraction of the people who wear glasses?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "29/110",
    answer_2: "31/88",
    answer_3: "4/11",
    answer_4: "43/99",
    answer_5: "49/110",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Ratios",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Arithmetic",
    level: 1,
    id: 16,
  },
  {
    question_id: 1,
    main_question_stem: "What is the Y intercept of the straight line?",
    subquestion1:
      "The line is at a perpendicular distance of 3 from the origin.",
    subquestion2: "The line has a slope â€˜-1â€™.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 3,
    id: 17,
  },
  {
    question_id: 2,
    main_question_stem: "What is the value of k?",
    subquestion1:
      "The line 2x+3y+6+k(9x-y+12)=0 is perpendicular to 7x+5y-4=0.",
    subquestion2: "The Y intercept of the line x+ky=4 is â€˜-8â€™.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "D",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 4,
    id: 18,
  },
  {
    question_id: 3,
    main_question_stem: "What is the value of (a-b)?",
    subquestion1: "The line passes through the points (3,-6) and (a,b).",
    subquestion2: "The line is parallel to 3x-3y+5=0.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 2,
    id: 19,
  },
  {
    question_id: 4,
    main_question_stem: "What is the area of the circle?",
    subquestion1:
      "The end-points of a diameter of the circle have coordinates (-3,-2) and (5,2).",
    subquestion2: "The centre of the circle is at (1,0).",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "A",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 2,
    id: 20,
  },
  {
    question_id: 5,
    main_question_stem: "What is the area of the circle?",
    subquestion1:
      "The circle passes through the points having coordinates (0,6) and (6,0).",
    subquestion2: "The circle passes through the point (0,0).",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 4,
    id: 21,
  },
  {
    question_id: 6,
    main_question_stem: "What are the coordinates of the centre of the circle",
    subquestion1:
      "The circle passes through the points having coordinates (1,2) and (5,4).",
    subquestion2: "The centre of the circle lies on the line y=2x+7",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 4,
    id: 22,
  },
  {
    question_id: 7,
    main_question_stem: "What is the value of k?",
    subquestion1: "The lines 2y+kx=16, y=x+5 and ky+x=9 are concurrent.",
    subquestion2: "k is an integer",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 2,
    id: 23,
  },
  {
    question_id: 8,
    main_question_stem: "What is the value of a?",
    subquestion1:
      "A line passing through the points (a,2a) and (-2,3) is perpendicular to the line 4x+3y+5=0.",
    subquestion2: "a is a positive number.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "A",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 2,
    id: 24,
  },
  {
    question_id: 9,
    main_question_stem: "What is the value of the Y coordinate of a point?",
    subquestion1:
      "The point is at a perpendicular distance of 3 units from the line 4x-3y=12.",
    subquestion2: "The point lies on the Y axis.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 4,
    id: 25,
  },
  {
    question_id: 10,
    main_question_stem:
      "The coordinates of A, B, C and D are (2,0),(9,0),(11,p) and (q,6) respectively. What is the length of BC?",
    subquestion1: "The slope of AD is 2.",
    subquestion2: "The slope of CD is 1/",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Co-ordinate Geometry",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Co-ordinate Geometry",
    level: 3,
    id: 26,
  },
  {
    question_id: 1,
    main_question_stem:
      "Two varieties of tea are mixed together, with each pound of the costlier variety being priced at $15 more than each pound of the cheaper variety. In what ratio were the two varieties of tea mixed?",
    subquestion1: "The average price of the mixture is $20 per pound.",
    subquestion2:
      "The average price of the mixture is $7 per pound cheaper than the costlier variety.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "B",
    Category: "Quant",
    "Sub-category": "Average",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 27,
  },
  {
    question_id: 1,
    main_question_stem:
      "A man covers a part of his journey at 20 miles per hour and the remaining at 30 miles per hour. What is the total distance covered by the man?",
    subquestion1: "The average speed of the man is 24 miles per hour.",
    subquestion2:
      "The ratio of the time for which he travelled at 20 miles per hour and that for which he travelled at 30 miles per hour is 3 :",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 28,
  },
  {
    question_id: 2,
    main_question_stem:
      "A travels from point P to point Q, while B travels from point Q to point P. At what time do they meet on the way?",
    subquestion1:
      "A starts his journey at 9:00 am while B starts his journey from 11:00 am.",
    subquestion2:
      "A takes 9 hours to reach point Q while B takes 6 hours to reach point P.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 4,
    id: 29,
  },
  {
    question_id: 3,
    main_question_stem:
      "A and B participate in a walkathon. If they start at the same time, does A win the contest?",
    subquestion1: "For every 5 steps taken by A, B takes 8 steps.",
    subquestion2: "3 steps of A are of the same length of 5 steps of B.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 2,
    id: 30,
  },
  {
    question_id: 4,
    main_question_stem:
      "A boy runs between points P and Q to and from a certain number of times. What is his average speed?",
    subquestion1:
      "The boy covers the distance from P to Q at a speed of 2 meters per second and returns at a speed of 4 meters per second and keeps on running to and from with double the speed in the previous trip.",
    subquestion2:
      "The maximum speed at which the boy can run is 16 meters per second.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 31,
  },
  {
    question_id: 5,
    main_question_stem:
      "A man covers a part of his journey by train and the rest by bus. What is the ratio of the distances he travelled by train and by bus?",
    subquestion1:
      "The speeds of the train and bus are 80 miles per hour and 60 miles per hour respectively.",
    subquestion2:
      "Had the man covered the entire journey by train at 80 miles per hour, he would have taken only 4/5 of the time he actually took.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 32,
  },
  {
    question_id: 6,
    main_question_stem:
      "A boy usually walks to school from his home at a uniform speed and reaches school on time. How early will he reach school if he cycles to school from his home?",
    subquestion1: "The boyâ€™s cycling speed is thrice his walking speed.",
    subquestion2:
      "Had the boy travelled in a car at a speed twice that of his cycling speed, he would have reached school 10 minutes before the time he reaches while cycling.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 4,
    id: 33,
  },
  {
    question_id: 7,
    main_question_stem:
      "A and B start from their homes at a previously agreed time and travel towards each other at their respective uniform speeds. On the way, they meet at a point P. If B had travelled at 20% higher speed, they would have met at another point Q. What is the distance between the homes of A and B?",
    subquestion1:
      "A and B travel at speeds of 9 miles per hour and 15 miles per hour, respectively.",
    subquestion2: "The distance between the points P and Q is 2 miles.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 4,
    id: 34,
  },
  {
    question_id: 8,
    main_question_stem:
      "How long does a man take to cover a certain distance travelling at his normal speed?",
    subquestion1:
      "If the man had travelled the same distance at 6 miles per hour greater than his normal speed, he would have taken 1 hour less than the time he would have taken while travelling at his normal speed.",
    subquestion2:
      "If the man had travelled the same distance at 4 miles per hour lower than his normal speed, he would have taken 1 hour more than the time he would have taken while travelling at his normal speed.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 5,
    id: 35,
  },
  {
    question_id: 9,
    main_question_stem:
      "A and B travel from points P and Q, respectively, towards point R, where P, Q and R lie along the same straight route. If point P lies 100 meters behind point Q, does A reach point R before B?",
    subquestion1: "The distance between the points Q and R is 500 meters.",
    subquestion2:
      "If A had started from Q and B had started from P, B would have been 100 meters behind A when A would have reached R.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Rate and Distance",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 36,
  },
  {
    question_id: 1,
    main_question_stem:
      "A student appeared for a number of tests, each test having maximum marks of 200. His average score is 70 greater than his lowest score in any test. However, the median score is 50 greater than the lowest score in any test. If the range of scores of the student is 150, and the number of tests is an odd number, what is the minimum number of tests that the student appeared for?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "3",
    answer_2: "5",
    answer_3: "Â Â Â Â  7",
    answer_4: "Â Â Â  9",
    answer_5: "Â Â Â Â  11",
    correct_answer: "B",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 3,
    id: 37,
  },
  {
    question_id: 2,
    main_question_stem:
      "Five people have some marbles with them. The numbers of marbles with them are 23, 45, 51, 66 and 73. If they redistribute the marbles among themselves such that the number of marbles with each is a distinct positive integer and the median value of the number of marbles is maximized, what is the range of the number of marbles with them?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "83",
    answer_2: "84",
    answer_3: "Â Â Â Â  85",
    answer_4: "Â Â Â  86",
    answer_5: "Â Â Â Â  88",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 3,
    id: 38,
  },
  {
    question_id: 3,
    main_question_stem:
      "The average of 7 numbers is 12. The average of the 4 smallest numbers in this set is 8, while the average of the 4 greatest numbers in this set is 20. How much greater is the sum of the 3 greatest numbers than the sum of the 3 smallest numbers?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "32",
    answer_2: "46",
    answer_3: "Â Â Â Â  48",
    answer_4: "Â Â Â  80",
    answer_5: "Â Â Â Â  84",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 2,
    id: 39,
  },
  {
    question_id: 4,
    main_question_stem:
      "The average age of the members of a club is greater than 32 years. If four of the members are 25 years old and none of the members are more than 60 years old, which of the following could be the number of members in the club?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "Only I",
    answer_2: "Only II",
    answer_3: "Only III",
    answer_4: "Both II and III",
    answer_5: "I, II and III",
    correct_answer: "D",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 5,
    id: 40,
  },
  {
    question_id: 5,
    main_question_stem:
      "For a set of 8 positive distinct integers, the mean, median, and range are calculated. If the smallest three numbers of the set are reduced by 2 each and the largest two are increased by 3 each, which of the following statements is correct?",
    subquestion1: "The mean of the set of numbers would change",
    subquestion2: "The median of the set of numbers would change",
    subquestion3: "The range of the set of numbers would change",
    answer_1: "Only I",
    answer_2: "Only II",
    answer_3: "Only III",
    answer_4: "Both II and III",
    answer_5: "I, II and III",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 4,
    id: 41,
  },
  {
    question_id: 6,
    main_question_stem:
      "The average of five distinct integers is 65. If the largest integer is 75, what is the maximum possible value of the smallest integer?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "60",
    answer_2: "61",
    answer_3: "Â Â Â Â  62",
    answer_4: "Â Â Â  63",
    answer_5: "Â Â Â Â  64",
    correct_answer: "B",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 3,
    id: 42,
  },
  {
    question_id: 7,
    main_question_stem:
      "The range of heights of students in Class A is 9 inches and that for Class B is 6 inches. The information contained in which of the following statements may be sufficient to determine the range of height of all the students from classes A and B?",
    subquestion1:
      "The tallest student in class B is 5 inches taller than the tallest student in class A",
    subquestion2:
      "The shortest student in class B is 8 inches shorter than the tallest student in class A",
    subquestion3:
      "The shortest student in class B is 8 inches shorter than the shortest student in class A",
    answer_1: "Only I",
    answer_2: "Only II",
    answer_3: "Only III",
    answer_4: "Both II and III",
    answer_5: "I, II and III",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 4,
    id: 43,
  },
  {
    question_id: 8,
    main_question_stem:
      "Four students contributed to a charity drive, and the average amount contributed by each student was $20. If no student gave more than $25 and all contributed different amounts, what is the maximum ratio of the amounts contributed by any two students?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "3",
    answer_2: "3.125",
    answer_3: "3.625",
    answer_4: "5",
    answer_5: "5.5",
    correct_answer: "B",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 2,
    id: 44,
  },
  {
    question_id: 9,
    main_question_stem:
      "For the set of numbers {x,y,(x+y),(x-4y),xy,2y}, if y>6 and the mean of the set equals (y+3), which of the following denotes the median of the above set?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "x+y",
    answer_2: "x/2+y",
    answer_3: "x+y/2",
    answer_4: "x-4y",
    answer_5: "(x+y)/2",
    correct_answer: "B",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 3,
    id: 45,
  },
  {
    question_id: 10,
    main_question_stem:
      "The mean of n terms is x. If the first term is increased by 1, the second by 2, the third by 3, and so on, which of the following denotes the new mean?",
    subquestion1: "",
    subquestion2: "",
    subquestion3: "",
    answer_1: "x+(n-1)/2",
    answer_2: "x+n/2",
    answer_3: "x+(n+1)/2",
    answer_4: "x+n-1",
    answer_5: "x+n",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Statistics",
    Quant_category_1: "Word problems",
    "Quant_category 2": "Statistics",
    level: 3,
    id: 46,
  },
  {
    question_id: 1,
    main_question_stem:
      "A teacher distributed some pens and some pencils evenly among the students in his class, with each student getting an equal number of pens and an equal number of pencils. How many students are there in the class?",
    subquestion1: "The teacher distributed 180 pens and 40 pencils.",
    subquestion2:
      "The total number of items received by each student is less than 15.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Numbers",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 4,
    id: 47,
  },
  {
    question_id: 2,
    main_question_stem:
      "The number 2135, when divided by a number n, leaves a remainder r. What is the value of n?",
    subquestion1:
      "The number 2315, when divided by n, also leaves the same remainder r.",
    subquestion2:
      "The number 2585, when divided by n, also leaves the same remainder r.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Numbers",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 48,
  },
  {
    question_id: 3,
    main_question_stem: "What is the remainder when 2n is divided by 8?",
    subquestion1: "n, when divided by 6, leaves remainder 5.",
    subquestion2: "3n, when divided by 6, leaves remainder 3.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "E",
    Category: "Quant",
    "Sub-category": "Numbers",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 49,
  },
  {
    question_id: 4,
    main_question_stem:
      "The remainder, when a number n is divided by 6, is p. The remainder, when the same number n is divided by 12, is q. Is p<q?",
    subquestion1: "n is a positive number having 8 as a factor.",
    subquestion2: "n is a positive number having 6 as a factor.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Numbers",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 5,
    id: 50,
  },
  {
    question_id: 5,
    main_question_stem: "Is n/12 an integer?",
    subquestion1: "n^2/144 is an integer.",
    subquestion2: "n/6 is an integer.",
    subquestion3: "",
    answer_1:
      "Statement (1) alone is sufficient but statement (2) alone is not sufficient",
    answer_2:
      "Statement (2) alone is sufficient but statement (1) alone is not sufficient",
    answer_3:
      "Both statements together are sufficient, but neither statement alone is sufficient",
    answer_4: "Each statement alone is sufficient",
    answer_5: "Statements (1) and (2) together are not sufficient",
    correct_answer: "C",
    Category: "Quant",
    "Sub-category": "Numbers",
    Quant_category_1: "Data Sufficiency",
    "Quant_category 2": "Arithmetic",
    level: 3,
    id: 51,
  },
];
//   {
//     question_id: 1,
//     main_question_stem:
//       "In a locality, there are thrice as many buses as cabs. 10% of the buses are air-conditioned while 60% of the cabs are air-conditioned. If there are only these 2 types of vehicles, what percentage of the vehicles are air-conditioned?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 0.225,
//     answer_2: 0.25,
//     answer_3: 0.3,
//     answer_4: 0.333,
//     answer_5: 0.36,
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 2,
//     main_question_stem:
//       "In a school, 20% of the boys learn French while 60% of the students who learn French are girls. If there are 100 boys, how many girls learn French?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 20,
//     answer_2: 24,
//     answer_3: 30,
//     answer_4: 36,
//     answer_5: 45,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 3,
//     main_question_stem:
//       "A and B need to do the laundry since their washing machine broke down. A can wash 1/3rd of the clothes in 30 minutes. Both A and B can wash all the clothes in 1 hour. What fraction of the clothes can B wash in 20 minutes?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "1/12",
//     answer_2: "1/9",
//     answer_3: "1/8",
//     answer_4: "1/6",
//     answer_5: "1/3",
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Rate and Work",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 4,
//     main_question_stem:
//       "A can write 10 programming codes in 15 hours, and B can write the same codes in 12 hours. If A and B work together on the codes, what fraction of the total work would B have done more than A after 3 hours?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "1/5",
//     answer_2: "3/10",
//     answer_3: "1/3",
//     answer_4: "9/20",
//     answer_5: "1/2",
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Rate and Work",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 5,
//     main_question_stem:
//       "A and B can paint 3 walls in 2 hours. Along with C, they can paint 5 walls in 3 hours. If A and C work at the same rate, how long would B take to paint 2 walls?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "1.5 hours",
//     answer_2: "1.8 hours",
//     answer_3: "2 hours",
//     answer_4: "2.5 hours",
//     answer_5: "3 hours",
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Rate and Work",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 6,
//     main_question_stem:
//       "Machines A and B can polish 3 articles in 2 hours and 5 articles every 4 hours. If the efficiency of A were tripled and that of B doubled, how long would the 2 machines together take to polish 70 articles?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "10 hours",
//     answer_2: "12 hours",
//     answer_3: "15 hours",
//     answer_4: "16 hours",
//     answer_5: "20 hours",
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Rate and Work",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 7,
//     main_question_stem:
//       "A and B can complete a work in 15 days. The same work can be completed by A and C in 10 days. How long would it take for B to complete the work alone?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 20,
//     answer_2: 25,
//     answer_3: 30,
//     answer_4: 35,
//     answer_5: 40,
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Rate and Work",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 8,
//     main_question_stem:
//       "A car travels from point A to point B at a speed of 60 mph and returns from point B to point A at a speed of 40 mph. What is the average speed for the entire journey?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 48,
//     answer_2: 50,
//     answer_3: 52,
//     answer_4: 54,
//     answer_5: 56,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Speed, Time, and Distance",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 9,
//     main_question_stem:
//       "A car travels from point A to point B at a speed of 60 mph and returns from point B to point A at a speed of 40 mph. What is the average speed for the entire journey?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 48,
//     answer_2: 50,
//     answer_3: 52,
//     answer_4: 54,
//     answer_5: 56,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Speed, Time, and Distance",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 10,
//     main_question_stem:
//       "A car travels from point A to point B at a speed of 60 mph and returns from point B to point A at a speed of 40 mph. What is the average speed for the entire journey?",
//     subquestion1: "1. 48",
//     subquestion2: "2. 50",
//     subquestion3: "3. 52",
//     answer_1: 48,
//     answer_2: 50,
//     answer_3: 52,
//     answer_4: 54,
//     answer_5: 56,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Speed, Time, and Distance",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 3,
//   },
//   {
//     question_id: 11,
//     main_question_stem:
//       "If 20% of a number is 40, what is 30% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 60,
//     answer_2: 70,
//     answer_3: 80,
//     answer_4: 90,
//     answer_5: 100,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 12,
//     main_question_stem:
//       "If a shirt originally costs $60 and is on sale for 20% off, what is the sale price of the shirt?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 45,
//     answer_2: 48,
//     answer_3: 52,
//     answer_4: 55,
//     answer_5: 58,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 13,
//     main_question_stem:
//       "If 25% of a number is 40, what is 20% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 32,
//     answer_2: 36,
//     answer_3: 40,
//     answer_4: 44,
//     answer_5: 48,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 14,
//     main_question_stem:
//       "If 40% of a number is 50, what is 50% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 60,
//     answer_2: 70,
//     answer_3: 80,
//     answer_4: 90,
//     answer_5: 100,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 15,
//     main_question_stem:
//       "If 30% of a number is 60, what is 25% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 48,
//     answer_2: 54,
//     answer_3: 60,
//     answer_4: 66,
//     answer_5: 72,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 16,
//     main_question_stem:
//       "If 15% of a number is 30, what is 40% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 80,
//     answer_2: 90,
//     answer_3: 100,
//     answer_4: 110,
//     answer_5: 120,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 17,
//     main_question_stem:
//       "If 12% of a number is 24, what is 6% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 12,
//     answer_2: 14,
//     answer_3: 16,
//     answer_4: 18,
//     answer_5: 20,
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 18,
//     main_question_stem:
//       "If 18% of a number is 36, what is 15% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 30,
//     answer_2: 33,
//     answer_3: 36,
//     answer_4: 39,
//     answer_5: 42,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 19,
//     main_question_stem:
//       "If 24% of a number is 48, what is 8% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 16,
//     answer_2: 18,
//     answer_3: 20,
//     answer_4: 22,
//     answer_5: 24,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 20,
//     main_question_stem:
//       "If 10% of a number is 20, what is 50% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 100,
//     answer_2: 120,
//     answer_3: 140,
//     answer_4: 160,
//     answer_5: 180,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },

//   {
//     question_id: 21,
//     main_question_stem:
//       "If 8% of a number is 24, what is 16% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 48,
//     answer_2: 56,
//     answer_3: 64,
//     answer_4: 72,
//     answer_5: 80,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 22,
//     main_question_stem:
//       "If 14% of a number is 35, what is 7% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 15,
//     answer_2: 20,
//     answer_3: 25,
//     answer_4: 30,
//     answer_5: 35,
//     correct_answer: "E",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 23,
//     main_question_stem:
//       "If 9% of a number is 45, what is 15% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 60,
//     answer_2: 65,
//     answer_3: 70,
//     answer_4: 75,
//     answer_5: 80,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 24,
//     main_question_stem:
//       "If 6% of a number is 36, what is 18% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 54,
//     answer_2: 60,
//     answer_3: 66,
//     answer_4: 72,
//     answer_5: 78,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 25,
//     main_question_stem:
//       "If 12% of a number is 60, what is 24% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 90,
//     answer_2: 96,
//     answer_3: 102,
//     answer_4: 108,
//     answer_5: 114,
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 26,
//     main_question_stem:
//       "If 16% of a number is 32, what is 32% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 48,
//     answer_2: 64,
//     answer_3: 80,
//     answer_4: 96,
//     answer_5: 112,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 27,
//     main_question_stem:
//       "If 5% of a number is 25, what is 15% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 45,
//     answer_2: 50,
//     answer_3: 55,
//     answer_4: 60,
//     answer_5: 65,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 28,
//     main_question_stem:
//       "If 20% of a number is 30, what is 25% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 35,
//     answer_2: 40,
//     answer_3: 45,
//     answer_4: 50,
//     answer_5: 55,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 29,
//     main_question_stem:
//       "If 25% of a number is 75, what is 50% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 100,
//     answer_2: 125,
//     answer_3: 150,
//     answer_4: 175,
//     answer_5: 200,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 30,
//     main_question_stem:
//       "If 30% of a number is 90, what is 10% of the same number?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 20,
//     answer_2: 30,
//     answer_3: 40,
//     answer_4: 50,
//     answer_5: 60,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Percentage",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },

//   {
//     question_id: 31,
//     main_question_stem:
//       "If a car travels 150 miles in 3 hours, what is its average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 45,
//     answer_2: 50,
//     answer_3: 55,
//     answer_4: 60,
//     answer_5: 65,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 32,
//     main_question_stem:
//       "If a train travels 240 miles in 4 hours, what is its average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 55,
//     answer_2: 60,
//     answer_3: 65,
//     answer_4: 70,
//     answer_5: 75,
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 33,
//     main_question_stem:
//       "If a plane travels 600 miles in 2 hours, what is its average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 250,
//     answer_2: 300,
//     answer_3: 350,
//     answer_4: 400,
//     answer_5: 450,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 34,
//     main_question_stem:
//       "If a cyclist travels 45 miles in 2.5 hours, what is the cyclist's average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 15,
//     answer_2: 17,
//     answer_3: 18,
//     answer_4: 20,
//     answer_5: 22,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 35,
//     main_question_stem:
//       "If a boat travels 120 miles in 6 hours, what is its average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 15,
//     answer_2: 18,
//     answer_3: 20,
//     answer_4: 22,
//     answer_5: 24,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 36,
//     main_question_stem:
//       "If a jogger runs 8 miles in 1 hour, what is the jogger's average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 4,
//     answer_2: 6,
//     answer_3: 8,
//     answer_4: 10,
//     answer_5: 12,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 37,
//     main_question_stem:
//       "If a plane travels 800 miles in 4 hours, what is its average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 100,
//     answer_2: 150,
//     answer_3: 200,
//     answer_4: 250,
//     answer_5: 300,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 38,
//     main_question_stem:
//       "If a car travels 360 miles in 6 hours, what is its average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 40,
//     answer_2: 50,
//     answer_3: 60,
//     answer_4: 70,
//     answer_5: 80,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 39,
//     main_question_stem:
//       "If a cyclist travels 30 miles in 1.5 hours, what is the cyclist's average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 15,
//     answer_2: 18,
//     answer_3: 20,
//     answer_4: 22,
//     answer_5: 24,
//     correct_answer: "A",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },
//   {
//     question_id: 40,
//     main_question_stem:
//       "If a boat travels 45 miles in 3 hours, what is its average speed in miles per hour (mph)?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 10,
//     answer_2: 12,
//     answer_3: 14,
//     answer_4: 16,
//     answer_5: 18,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 1,
//   },

//   {
//     question_id: 41,
//     main_question_stem:
//       "A train travels from City A to City B at an average speed of 60 miles per hour (mph). If the distance between the two cities is 240 miles, how long will it take the train to reach City B?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 2,
//     answer_2: 3,
//     answer_3: 4,
//     answer_4: 5,
//     answer_5: 6,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 42,
//     main_question_stem:
//       "A car travels from Town X to Town Y at an average speed of 45 miles per hour (mph). If the distance between the two towns is 135 miles, how long will it take the car to reach Town Y?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 2,
//     answer_2: 3,
//     answer_3: 4,
//     answer_4: 5,
//     answer_5: 6,
//     correct_answer: "C",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 43,
//     main_question_stem:
//       "A cyclist rides at an average speed of 18 miles per hour (mph). If the cyclist rides for 2 hours, how far will they have traveled?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 18,
//     answer_2: 24,
//     answer_3: 30,
//     answer_4: 36,
//     answer_5: 42,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 44,
//     main_question_stem:
//       "A plane travels at an average speed of 500 miles per hour (mph). How long will it take the plane to travel 2,500 miles?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 3,
//     answer_2: 4,
//     answer_3: 5,
//     answer_4: 6,
//     answer_5: 7,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 45,
//     main_question_stem:
//       "A motorcyclist rides at an average speed of 65 miles per hour (mph). If the motorcyclist rides for 3 hours, how far will they have traveled?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 130,
//     answer_2: 150,
//     answer_3: 180,
//     answer_4: 195,
//     answer_5: 210,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 46,
//     main_question_stem:
//       "A car travels at an average speed of 55 miles per hour (mph). If the car travels for 5 hours, how far will it have traveled?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 200,
//     answer_2: 225,
//     answer_3: 250,
//     answer_4: 275,
//     answer_5: 300,
//     correct_answer: "E",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 47,
//     main_question_stem:
//       "A train travels at an average speed of 70 miles per hour (mph). If it takes the train 3 hours to reach its destination, how far did it travel?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 190,
//     answer_2: 200,
//     answer_3: 210,
//     answer_4: 220,
//     answer_5: 230,
//     correct_answer: "B",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 48,
//     main_question_stem:
//       "A cyclist rides at an average speed of 15 miles per hour (mph). If the cyclist rides for 4 hours, how far will they have traveled?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 45,
//     answer_2: 50,
//     answer_3: 55,
//     answer_4: 60,
//     answer_5: 65,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 49,
//     main_question_stem:
//       "A car travels at an average speed of 70 miles per hour (mph). If the car travels for 3.5 hours, how far will it have traveled?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 210,
//     answer_2: 220,
//     answer_3: 230,
//     answer_4: 240,
//     answer_5: 250,
//     correct_answer: "D",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },
//   {
//     question_id: 50,
//     main_question_stem:
//       "A bus travels at an average speed of 50 miles per hour (mph). If the bus travels for 6 hours, how far will it have traveled?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 200,
//     answer_2: 250,
//     answer_3: 300,
//     answer_4: 350,
//     answer_5: 400,
//     correct_answer: "E",
//     Category: "Quant",
//     "Sub-category": "Speed, Distance, and Time",
//     Quant_category_1: "Word problems",
//     Quant_category_2: "Arithmetic",
//     level: 2,
//   },

//   {
//     question_id: 51,
//     main_question_stem:
//       "If you have a balance scale and three boxes that appear identical, but one of them contains counterfeit coins that are slightly heavier than real coins, how can you determine which box contains the counterfeit coins using the scale only once?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "A",
//     answer_2: "B",
//     answer_3: "C",
//     answer_4: "D",
//     answer_5: "E",
//     correct_answer: "A",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 3,
//   },
//   {
//     question_id: 52,
//     main_question_stem:
//       "You have a balance scale and eight coins. One of the coins is slightly heavier than the others. How can you find the heavier coin using the scale only twice?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "A",
//     answer_2: "B",
//     answer_3: "C",
//     answer_4: "D",
//     answer_5: "E",
//     correct_answer: "B",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 3,
//   },
//   {
//     question_id: 53,
//     main_question_stem:
//       "You are given eight balls that all look identical. However, one of them is slightly heavier than the rest. You also have a balance scale. How can you find the heavier ball using the scale only twice?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "A",
//     answer_2: "B",
//     answer_3: "C",
//     answer_4: "D",
//     answer_5: "E",
//     correct_answer: "C",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 3,
//   },
//   {
//     question_id: 54,
//     main_question_stem:
//       "You have 12 balls that all appear identical, but one of them is either slightly heavier or slightly lighter than the others. You also have a balance scale. How can you identify the odd ball and determine whether it's heavier or lighter in only three weighings?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "A",
//     answer_2: "B",
//     answer_3: "C",
//     answer_4: "D",
//     answer_5: "E",
//     correct_answer: "D",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 4,
//   },
//   {
//     question_id: 55,
//     main_question_stem:
//       "You have nine balls that all look identical, but one of them is either slightly heavier or slightly lighter than the others. You also have a balance scale. How can you identify the odd ball and determine whether it's heavier or lighter in only two weighings?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "A",
//     answer_2: "B",
//     answer_3: "C",
//     answer_4: "D",
//     answer_5: "E",
//     correct_answer: "B",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 4,
//   },
//   {
//     question_id: 56,
//     main_question_stem:
//       "You have eight balls that all appear identical, but one of them is either slightly heavier or slightly lighter than the others. You also have a balance scale. How can you identify the odd ball and determine whether it's heavier or lighter in only two weighings?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "A",
//     answer_2: "B",
//     answer_3: "C",
//     answer_4: "D",
//     answer_5: "E",
//     correct_answer: "A",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 4,
//   },
//   {
//     question_id: 57,
//     main_question_stem:
//       "You have 25 identical-looking coins, and you know that one of them is counterfeit and slightly lighter than the others. You also have a balance scale. How can you find the counterfeit coin using the scale only seven times?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: "A",
//     answer_2: "B",
//     answer_3: "C",
//     answer_4: "D",
//     answer_5: "E",
//     correct_answer: "D",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 5,
//   },
//   {
//     question_id: 58,
//     main_question_stem:
//       "You have 27 identical-looking coins, and you know that one of them is counterfeit and slightly lighter than the others. You also have a balance scale. What is the minimum number of weighings needed to find the counterfeit coin?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 2,
//     answer_2: 3,
//     answer_3: 4,
//     answer_4: 5,
//     answer_5: 6,
//     correct_answer: "B",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 5,
//   },
//   {
//     question_id: 59,
//     main_question_stem:
//       "You have 12 identical-looking coins, and you know that one of them is counterfeit and slightly lighter than the others. You also have a balance scale. What is the minimum number of weighings needed to find the counterfeit coin?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 2,
//     answer_2: 3,
//     answer_3: 4,
//     answer_4: 5,
//     answer_5: 6,
//     correct_answer: "B",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 4,
//   },
//   {
//     question_id: 60,
//     main_question_stem:
//       "You have eight identical-looking coins, and you know that one of them is counterfeit and slightly lighter than the others. You also have a balance scale. What is the minimum number of weighings needed to find the counterfeit coin?",
//     subquestion1: "",
//     subquestion2: "",
//     subquestion3: "",
//     answer_1: 2,
//     answer_2: 3,
//     answer_3: 4,
//     answer_4: 5,
//     answer_5: 6,
//     correct_answer: "A",
//     Category: "Logic",
//     "Sub-category": "Logical Puzzles",
//     level: 3,
//   },
// ];
